//---------------------------------------------------------------------------------------------
// This file was AUTO-GENERATED by "Service Contracts" Xomega.Net generator.
//
// Manual CHANGES to this file WILL BE LOST when the code is regenerated.
//---------------------------------------------------------------------------------------------

using System.Collections.Generic;

namespace AdventureWorks.Services
{
    #region ICustomerService interface

    public interface ICustomerService
    {

        ///<summary>
        /// Reads a list of Customer objects based on the specified criteria.
        ///</summary>
        IEnumerable<Customer_ReadListOutput> ReadList(Customer_ReadListInput_Criteria _criteria);

    }
    #endregion

    #region Customer_ReadListInput_Criteria structure

    ///<summary>
    /// Structure of parameter Criteria of the input structure of operation ICustomerService.ReadList.
    ///</summary>
    public class Customer_ReadListInput_Criteria
    {
        public int? TerritoryId { get; set; }
        public string PersonNameOperator { get; set; }
        public string PersonName { get; set; }
        public string StoreNameOperator { get; set; }
        public string StoreName { get; set; }
        public string AccountNumberOperator { get; set; }
        public string AccountNumber { get; set; }
    }
    #endregion

    #region Customer_ReadListOutput structure

    ///<summary>
    /// The output structure of operation ICustomerService.ReadList.
    ///</summary>
    public class Customer_ReadListOutput
    {
        public int CustomerId { get; set; }
        public int? StoreId { get; set; }
        public string StoreName { get; set; }
        public int? PersonId { get; set; }
        public string PersonName { get; set; }
        public string AccountNumber { get; set; }
        public int? TerritoryId { get; set; }
    }
    #endregion

}