//---------------------------------------------------------------------------------------------
// This file was AUTO-GENERATED by "Lookup Cache Loaders" Xomega.Net generator.
//
// Manual CHANGES to this file WILL BE LOST when the code is regenerated.
//---------------------------------------------------------------------------------------------

using Microsoft.Extensions.DependencyInjection;
using Xomega.Framework.Lookup;

namespace AdventureWorks.Services
{
    public static class LookupCacheLoaders
    {
        public static void AddLookupCacheLoaders(this IServiceCollection container)
        {
            container.AddSingleton<ILookupCacheLoader, ProductReadListCacheLoader>();
            container.AddSingleton<ILookupCacheLoader, ProductSubcategoryReadListCacheLoader>();
            container.AddSingleton<ILookupCacheLoader, ShipMethodReadListCacheLoader>();
            container.AddSingleton<ILookupCacheLoader, SalesPersonReadListCacheLoader>();
            container.AddSingleton<ILookupCacheLoader, SalesReasonReadListCacheLoader>();
            container.AddSingleton<ILookupCacheLoader, SalesTerritoryReadListCacheLoader>();
            container.AddSingleton<ILookupCacheLoader, SpecialOfferReadListCacheLoader>();
        }
    }
}