//---------------------------------------------------------------------------------------------
// This file was AUTO-GENERATED by "ASP.NET Views" Xomega.Net generator.
//
// Manual CHANGES to this file WILL BE LOST when the code is regenerated.
//---------------------------------------------------------------------------------------------

namespace AdventureWorks.Client.Web
{
    public partial class CustomerListViewPage
    {
        protected global::System.Web.UI.WebControls.Content Main;
        protected global::AdventureWorks.Client.Web.CustomerListView uclCustomerListView;
    }
}