//---------------------------------------------------------------------------------------------
// This file was AUTO-GENERATED by "ASP.NET Views" Xomega.Net generator.
//
// Manual CHANGES to this file WILL BE LOST when the code is regenerated.
//---------------------------------------------------------------------------------------------

using Microsoft.Extensions.DependencyInjection;
using System;
using System.Web.UI.WebControls;
using AdventureWorks.Client.ViewModels;
using Xomega.Framework.Web;

namespace AdventureWorks.Client.Web
{
    public partial class SalesOrderListView : WebSearchView
    {

        protected SalesOrderListViewModel viewModel { get { return Model as SalesOrderListViewModel; } }

        public SalesOrderListView()
        {
            Model = ServiceProvider.GetService<SalesOrderListViewModel>();
        }

        protected override void OnInit(EventArgs e)
        {
            base.OnInit(e);
            Split();
            SubscribeToChildEvents(uclSalesOrderView);
        }

        protected override void OnPreRender(EventArgs e)
        {
            base.OnPreRender(e);
            if (viewModel == null) return;
            lnkNew.Enabled = viewModel.lnkNew_Enabled();
        }

        protected virtual void lnkDetails_Click(object sender, CommandEventArgs e)
        {
            if (viewModel != null)
                viewModel.lnkDetails_Command(uclSalesOrderView, null, int.Parse(e.CommandArgument.ToString()));
        }

        protected virtual void lnkNew_Click(object sender, CommandEventArgs e)
        {
            if (viewModel != null)
                viewModel.lnkNew_Command(uclSalesOrderView, null);
        }

        public virtual void lnkPermaLink_Click(object sender, EventArgs e)
        {
            if (viewModel != null && viewModel.List != null && viewModel.List.CriteriaObject != null)
                Response.Redirect(WebUtil.AddQueryString(Request.RawUrl, viewModel.List.CriteriaObject.ToNameValueCollection()));
        }
    }
}