//---------------------------------------------------------------------------------------------
// This file was AUTO-GENERATED by "ASP.NET Views" Xomega.Net generator.
//
// Manual CHANGES to this file WILL BE LOST when the code is regenerated.
//---------------------------------------------------------------------------------------------

using Microsoft.Extensions.DependencyInjection;
using System;
using System.Web.UI.WebControls;
using AdventureWorks.Client.ViewModels;
using Xomega.Framework.Web;

namespace AdventureWorks.Client.Web
{
    public partial class SalesOrderView : WebDetailsView
    {

        protected SalesOrderViewModel viewModel { get { return Model as SalesOrderViewModel; } }

        public SalesOrderView()
        {
            Model = ServiceProvider.GetService<SalesOrderViewModel>();
        }

        protected override void OnInit(EventArgs e)
        {
            base.OnInit(e);
            SubscribeToChildEvents(uclCustomerListView);
            SubscribeToChildEvents(uclSalesOrderDetailView);
        }

        protected override void OnPreRender(EventArgs e)
        {
            base.OnPreRender(e);
            if (viewModel == null) return;
            lnkCustomerLookupLookUp.Enabled = viewModel.lnkCustomerLookupLookUp_Enabled();
            lnkDetailNew.Enabled = viewModel.lnkDetailNew_Enabled();
        }

        protected virtual void lnkCustomerLookupLookUp_Click(object sender, CommandEventArgs e)
        {
            if (viewModel != null)
                viewModel.lnkCustomerLookupLookUp_Command(uclCustomerListView, null);
        }

        protected virtual void lnkDetailDetails_Click(object sender, CommandEventArgs e)
        {
            if (viewModel != null)
                viewModel.lnkDetailDetails_Command(uclSalesOrderDetailView, null, int.Parse(e.CommandArgument.ToString()));
        }

        protected virtual void lnkDetailNew_Click(object sender, CommandEventArgs e)
        {
            if (viewModel != null)
                viewModel.lnkDetailNew_Command(uclSalesOrderDetailView, null);
        }
    }
}