//---------------------------------------------------------------------------------------------
// This file was AUTO-GENERATED by "EF Domain Objects" Xomega.Net generator.
//
// Manual CHANGES to this file WILL BE LOST when the code is regenerated.
//---------------------------------------------------------------------------------------------

using System;

namespace AdventureWorks.Services.Entities
{
    ///<summary>
    /// Lookup table containing the types of business entity contacts.
    ///</summary>
    public partial class ContactType
    {
        public ContactType()
        {
        }

        #region Properties

        public int ContactTypeId  { get; set; }

        ///<summary>
        /// Contact type description.
        ///</summary>
        public string Name  { get; set; }

        ///<summary>
        /// Date and time the record was last updated.
        ///</summary>
        public DateTime ModifiedDate  { get; set; }

        #endregion
    }
}