//---------------------------------------------------------------------------------------------
// This file was AUTO-GENERATED by "EF Domain Objects" Xomega.Net generator.
//
// Manual CHANGES to this file WILL BE LOST when the code is regenerated.
//---------------------------------------------------------------------------------------------

using System;

namespace AdventureWorks.Services.Entities
{
    ///<summary>
    /// Lookup table containing the ISO standard codes for countries and regions.
    ///</summary>
    public partial class CountryRegion
    {
        public CountryRegion()
        {
        }

        #region Properties

        public string CountryRegionCode  { get; set; }

        ///<summary>
        /// Country or region name.
        ///</summary>
        public string Name  { get; set; }

        ///<summary>
        /// Date and time the record was last updated.
        ///</summary>
        public DateTime ModifiedDate  { get; set; }

        #endregion
    }
}