//---------------------------------------------------------------------------------------------
// This file was AUTO-GENERATED by "EF Domain Objects" Xomega.Net generator.
//
// Manual CHANGES to this file WILL BE LOST when the code is regenerated.
//---------------------------------------------------------------------------------------------

using System;

namespace AdventureWorks.Services.Entities
{
    ///<summary>
    /// One way hashed authentication information
    ///</summary>
    public partial class Password
    {
        public Password()
        {
        }

        #region Properties

        public int BusinessEntityId  { get; set; }

        ///<summary>
        /// Password for the e-mail account.
        ///</summary>
        public string PasswordHash  { get; set; }

        ///<summary>
        /// Random value concatenated with the password string before the password is hashed.
        ///</summary>
        public string PasswordSalt  { get; set; }

        ///<summary>
        /// ROWGUIDCOL number uniquely identifying the record. Used to support a merge replication sample.
        ///</summary>
        public Guid Rowguid  { get; set; }

        ///<summary>
        /// Date and time the record was last updated.
        ///</summary>
        public DateTime ModifiedDate  { get; set; }

        #endregion

        #region Navigation Properties

        ///<summary>
        /// Person object referenced by the field BusinessEntityId.
        ///</summary>
        public virtual Person BusinessEntityObject { get; set; }

        #endregion
    }
}