//---------------------------------------------------------------------------------------------
// This file was AUTO-GENERATED by "EF Domain Objects" Xomega.Net generator.
//
// Manual CHANGES to this file WILL BE LOST when the code is regenerated.
//---------------------------------------------------------------------------------------------

using System;

namespace AdventureWorks.Services.Entities
{
    ///<summary>
    /// Type of phone number of a person.
    ///</summary>
    public partial class PhoneNumberType
    {
        public PhoneNumberType()
        {
        }

        #region Properties

        public int PhoneNumberTypeId  { get; set; }

        ///<summary>
        /// Name of the telephone number type
        ///</summary>
        public string Name  { get; set; }

        ///<summary>
        /// Date and time the record was last updated.
        ///</summary>
        public DateTime ModifiedDate  { get; set; }

        #endregion
    }
}