//---------------------------------------------------------------------------------------------
// This file was AUTO-GENERATED by "Service Contracts" Xomega.Net generator.
//
// Manual CHANGES to this file WILL BE LOST when the code is regenerated.
//---------------------------------------------------------------------------------------------


namespace AdventureWorks.Services
{
    #region AddressKey structure

    ///<summary>
    /// Address key information
    ///</summary>
    public class AddressKey
    {
        public int AddressId { get; set; }
    }
    #endregion

    #region AddressInfo structure

    ///<summary>
    /// Full address information
    ///</summary>
    public class AddressInfo
    {
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string CityState { get; set; }
        public string PostalCode { get; set; }
        public string Country { get; set; }
    }
    #endregion

}