//---------------------------------------------------------------------------------------------
// This file was AUTO-GENERATED by "EF Domain Objects" Xomega.Net generator.
//
// Manual CHANGES to this file WILL BE LOST when the code is regenerated.
//---------------------------------------------------------------------------------------------

using System;

namespace AdventureWorks.Services.Entities
{
    ///<summary>
    /// Sales territory lookup table.
    ///</summary>
    public partial class SalesTerritory
    {
        public SalesTerritory()
        {
        }

        #region Properties

        public int TerritoryId  { get; set; }

        ///<summary>
        /// Sales territory description
        ///</summary>
        public string Name  { get; set; }

        ///<summary>
        /// ISO standard country or region code. Foreign key to CountryRegion.CountryRegionCode. 
        ///</summary>
        public string CountryRegionCode  { get; set; }

        ///<summary>
        /// Geographic area to which the sales territory belong.
        ///</summary>
        public string Group  { get; set; }

        ///<summary>
        /// Sales in the territory year to date.
        ///</summary>
        public decimal SalesYtd  { get; set; }

        ///<summary>
        /// Sales in the territory the previous year.
        ///</summary>
        public decimal SalesLastYear  { get; set; }

        ///<summary>
        /// Business costs in the territory year to date.
        ///</summary>
        public decimal CostYtd  { get; set; }

        ///<summary>
        /// Business costs in the territory the previous year.
        ///</summary>
        public decimal CostLastYear  { get; set; }

        ///<summary>
        /// ROWGUIDCOL number uniquely identifying the record. Used to support a merge replication sample.
        ///</summary>
        public Guid Rowguid  { get; set; }

        ///<summary>
        /// Date and time the record was last updated.
        ///</summary>
        public DateTime ModifiedDate  { get; set; }

        #endregion

        #region Navigation Properties

        ///<summary>
        /// CountryRegion object referenced by the field CountryRegionCode.
        ///</summary>
        public virtual CountryRegion CountryRegionCodeObject { get; set; }

        #endregion
    }
}