//---------------------------------------------------------------------------------------------
// This file was AUTO-GENERATED by "EF Domain Objects" Xomega.Net generator.
//
// Manual CHANGES to this file WILL BE LOST when the code is regenerated.
//---------------------------------------------------------------------------------------------

using System;

namespace AdventureWorks.Services.Entities
{
    ///<summary>
    /// Sales representative current information.
    ///</summary>
    public partial class SalesPerson
    {
        public SalesPerson()
        {
        }

        #region Properties

        public int BusinessEntityId  { get; set; }

        ///<summary>
        /// Territory currently assigned to. Foreign key to SalesTerritory.SalesTerritoryID.
        ///</summary>
        public int? TerritoryId  { get; set; }

        ///<summary>
        /// Projected yearly sales.
        ///</summary>
        public decimal? SalesQuota  { get; set; }

        ///<summary>
        /// Bonus due if quota is met.
        ///</summary>
        public decimal Bonus  { get; set; }

        ///<summary>
        /// Commision percent received per sale.
        ///</summary>
        public decimal CommissionPct  { get; set; }

        ///<summary>
        /// Sales total year to date.
        ///</summary>
        public decimal SalesYtd  { get; set; }

        ///<summary>
        /// Sales total of previous year.
        ///</summary>
        public decimal SalesLastYear  { get; set; }

        ///<summary>
        /// ROWGUIDCOL number uniquely identifying the record. Used to support a merge replication sample.
        ///</summary>
        public Guid Rowguid  { get; set; }

        ///<summary>
        /// Date and time the record was last updated.
        ///</summary>
        public DateTime ModifiedDate  { get; set; }

        #endregion

        #region Navigation Properties

        ///<summary>
        /// Employee object referenced by the field BusinessEntityId.
        ///</summary>
        public virtual Employee BusinessEntityObject { get; set; }

        ///<summary>
        /// SalesTerritory object referenced by the field TerritoryId.
        ///</summary>
        public virtual SalesTerritory TerritoryObject { get; set; }

        #endregion
    }
}