//---------------------------------------------------------------------------------------------
// This file was AUTO-GENERATED by "EF Domain Objects" Xomega.Net generator.
//
// Manual CHANGES to this file WILL BE LOST when the code is regenerated.
//---------------------------------------------------------------------------------------------


namespace AdventureWorks.Services.Entities
{
    ///<summary>
    /// Tracking event lookup table.
    ///</summary>
    public partial class TrackingEvent
    {
        public TrackingEvent()
        {
        }

        #region Properties

        public int TrackingEventId  { get; set; }

        ///<summary>
        /// Tracking event name.
        ///</summary>
        public string EventName  { get; set; }

        #endregion
    }
}