//---------------------------------------------------------------------------------------------
// This file was AUTO-GENERATED by "WPF Views" Xomega.Net generator.
//
// Manual CHANGES to this file WILL BE LOST when the code is regenerated.
//---------------------------------------------------------------------------------------------

using Microsoft.Extensions.DependencyInjection;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Input;
using Xomega.Framework.Views;
using AdventureWorks.Client.ViewModels;

namespace AdventureWorks.Client.Wpf
{
    public partial class SalesOrderListView
    {
        public SalesOrderListView()
        {
            lnkDetails_Command = new RelayCommand<int?>(lnkDetails_Execute, lnkDetails_Enabled);
            lnkNew_Command = new RelayCommand<object>(lnkNew_Execute, lnkNew_Enabled);
            InitializeComponent();
        }

        #region lnkDetails_Command

        public ICommand lnkDetails_Command { get; set; }

        public virtual void lnkDetails_Execute(int? row)
        {
            SalesOrderListViewModel vm = Model as SalesOrderListViewModel;
            if (vm == null) return;
            WPFView cur = pnlDetails.Content as SalesOrderView;
            WPFView tgt = cur ?? vm.ServiceProvider.GetService<SalesOrderView>();
            tgt.Owner = this;
            vm.lnkDetails_Command(tgt, cur, row.Value);
        }
        public virtual bool lnkDetails_Enabled(int? row)
        {
            SalesOrderListViewModel c = Model as SalesOrderListViewModel;
            return c == null ? false : c.lnkDetails_Enabled(row.Value);
        }
        #endregion

        #region lnkNew_Command

        public ICommand lnkNew_Command { get; set; }

        public virtual void lnkNew_Execute(object arg)
        {
            SalesOrderListViewModel vm = Model as SalesOrderListViewModel;
            if (vm == null) return;
            WPFView cur = pnlDetails.Content as SalesOrderView;
            WPFView tgt = cur ?? vm.ServiceProvider.GetService<SalesOrderView>();
            tgt.Owner = this;
            vm.lnkNew_Command(tgt, cur);
        }
        public virtual bool lnkNew_Enabled(object arg)
        {
            SalesOrderListViewModel c = Model as SalesOrderListViewModel;
            return c == null ? false : c.lnkNew_Enabled();
        }
        #endregion

        protected override Button CloseButton { get { return btnClose; } }

        protected override Button SearchButton { get { return btnSearch; } }
        protected override Button ResetButton { get { return btnReset; } }
        protected override Button SelectButton { get { return btnSelect; } }

        protected override ItemsControl ResultsGrid { get { return gridResults; } }
        protected override IAppliedCriteriaPanel AppliedCriteriaPanel { get { return pnlAppliedCriteria; } }
        protected override ICollapsiblePanel CriteriaExpander { get { return new ExpanderCollapsiblePanel(pnlCriteria); } }
        protected override FrameworkElement CriteriaPanel { get { return pnlCriteria; } }
        protected override ContentControl ChildPanel { get { return pnlDetails; } }
    }
}