//---------------------------------------------------------------------------------------------
// This file was AUTO-GENERATED by "ASP.NET Views" Xomega.Net generator.
//
// Manual CHANGES to this file WILL BE LOST when the code is regenerated.
//---------------------------------------------------------------------------------------------

using Microsoft.Extensions.DependencyInjection;
using System;
using System.Web.UI.WebControls;
using AdventureWorks.Client.ViewModels;
using Xomega.Framework.Web;

namespace AdventureWorks.Client.Web
{
    public partial class LoginView : WebDetailsView
    {

        protected LoginViewModel viewModel { get { return Model as LoginViewModel; } }

        public LoginView()
        {
            Model = ServiceProvider.GetService<LoginViewModel>();
        }

        protected override void OnInit(EventArgs e)
        {
            base.OnInit(e);
        }

        protected override void OnPreRender(EventArgs e)
        {
            base.OnPreRender(e);
            if (viewModel == null) return;
        }
    }
}