//---------------------------------------------------------------------------------------------
// This file was AUTO-GENERATED by "Service Contracts" Xomega.Net generator.
//
// Manual CHANGES to this file WILL BE LOST when the code is regenerated.
//---------------------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Runtime.Serialization;
using System.ServiceModel;
using Xomega.Framework;

namespace AdventureWorks.Services
{
    #region IBusinessEntityAddressService interface

    ///<summary>
    /// Cross-reference table mapping customers, vendors, and employees to their addresses.
    ///</summary>
    [ServiceContract]
    public interface IBusinessEntityAddressService
    {

        [OperationContract]
        [FaultContract(typeof(ErrorList))]
        IEnumerable<BusinessEntityAddress_ReadListOutput> ReadList(int _businessEntityId);

    }
    #endregion

    #region BusinessEntityAddress_ReadListOutput structure

    ///<summary>
    /// The output structure of operation IBusinessEntityAddressService.ReadList.
    ///</summary>
    [DataContract]
    public class BusinessEntityAddress_ReadListOutput
    {
        [DataMember]
        public int AddressId { get; set; }
        [DataMember]
        public string AddressType { get; set; }
        [DataMember]
        public string AddressLine1 { get; set; }
        [DataMember]
        public string AddressLine2 { get; set; }
        [DataMember]
        public string City { get; set; }
        [DataMember]
        public string State { get; set; }
        [DataMember]
        public string PostalCode { get; set; }
        [DataMember]
        public string Country { get; set; }
    }
    #endregion

}