//---------------------------------------------------------------------------------------------
// This file was AUTO-GENERATED by "WCF Service Contracts" Xomega.Net generator.
//
// Manual CHANGES to this file WILL BE LOST when the code is regenerated.
//---------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.ServiceModel;
using System.ServiceModel.Web;
using Xomega.Framework;

namespace AdventureWorks.Services
{
    #region CustomerInfo structure

    [DataContract]
    public class CustomerInfo
    {
        [DataMember]
        public int CustomerId { get; set; }
        [DataMember]
        public int? StoreId { get; set; }
        [DataMember]
        public string StoreName { get; set; }
        [DataMember]
        public int? PersonId { get; set; }
        [DataMember]
        public string PersonName { get; set; }
        [DataMember]
        public string AccountNumber { get; set; }
        [DataMember]
        public int? TerritoryId { get; set; }
        [DataMember]
        public int? BillToAddressId { get; set; }
        [DataMember]
        public int? ShipToAddressId { get; set; }
    }
    #endregion

    #region CustomerUpdate structure

    [DataContract]
    public class CustomerUpdate
    {
        [DataMember]
        public int CustomerId { get; set; }
        [DataMember]
        public int? BillToAddressId { get; set; }
        [DataMember]
        public int? ShipToAddressId { get; set; }
    }
    #endregion

    #region PaymentInfo structure

    [DataContract]
    public class PaymentInfo
    {
        [DataMember]
        public decimal SubTotal { get; set; }
        [DataMember]
        public int ShipMethodId { get; set; }
        [DataMember]
        public decimal TaxAmt { get; set; }
        [DataMember]
        public decimal Freight { get; set; }
        [DataMember]
        public decimal TotalDue { get; set; }
        [DataMember]
        public DateTime DueDate { get; set; }
        [DataMember]
        public string CurrencyRate { get; set; }
        [DataMember]
        public int? CreditCardId { get; set; }
        [DataMember]
        public string CreditCardApprovalCode { get; set; }
    }
    #endregion

    #region PaymentUpdate structure

    [DataContract]
    public class PaymentUpdate
    {
        [DataMember]
        public int ShipMethodId { get; set; }
        [DataMember]
        public DateTime DueDate { get; set; }
        [DataMember]
        public int? CreditCardId { get; set; }
        [DataMember]
        public string CreditCardApprovalCode { get; set; }
    }
    #endregion

    #region SalesInfo structure

    [DataContract]
    public class SalesInfo
    {
        [DataMember]
        public int? TerritoryId { get; set; }
        [DataMember]
        public int? SalesPersonId { get; set; }
        [DataMember]
        public IEnumerable<int> SalesReason { get; set; }
    }
    #endregion

}