//---------------------------------------------------------------------------------------------
// This file was AUTO-GENERATED by "Enumeration Constants" Xomega.Net generator.
//
// Manual CHANGES to this file WILL BE LOST when the code is regenerated.
//---------------------------------------------------------------------------------------------

namespace AdventureWorks.Enumerations
{
    #region Operators
    ///<summary>
    /// A list of operators to be used with filter criteria.
    ///</summary>
    public class Operators
    {
        ///<summary>
        /// Enumeration name used for storing it in a lookup cache.
        ///</summary>
        public const string EnumName = "operators";

        ///<summary>
        /// Additional attributes for enumeration 'operators'.
        ///</summary>
        public class Attributes
        {
            ///<summary>
            /// Defines the sort order of the operators with respect to other operators.
            ///</summary>
            public const string SortOrder = "sort order";
            ///<summary>
            /// The number of additional data properties that the operator needs.
            /// 0 (default) means it needs no additional values, 1 means it needs a value and 2 is for ranges that need both ends.
            ///</summary>
            public const string AddlProps = "addl props";
            ///<summary>
            /// 1 if the additional property can be multi-valued, 0 otherwise.
            ///</summary>
            public const string Multival = "multival";
            ///<summary>
            /// Fully qualified type of the additional property, which this operator applies to.
            /// It will also apply to all subclasses of this type. Multiple types can be specified.
            ///</summary>
            public const string Type = "type";
            ///<summary>
            /// Fully qualified type of the additional property, which this operator does not apply to.
            /// It won't also apply to all subclasses of this type. Multiple exclude types can be specified.
            /// Exclude types should be generally more concrete than include types.
            ///</summary>
            public const string ExcludeType = "exclude type";
            ///<summary>
            /// 1 for null checks, otherwise 0 (default).
            ///</summary>
            public const string NullCheck = "null check";
        }

        ///<summary>
        /// Checks if the target value is blank.
        ///</summary>
        public const string IsNull = "NULL";
        ///<summary>
        /// Checks if the target value is not blank.
        ///</summary>
        public const string IsNotNull = "NOTNULL";
        ///<summary>
        /// Checks if the target value is equal to the specified value.
        ///</summary>
        public const string IsEqualTo = "IS";
        ///<summary>
        /// Checks if the target value is not equal to the specified value.
        ///</summary>
        public const string IsNotEqualTo = "ISNOT";
        ///<summary>
        /// Checks if the target value is one of the values listed.
        ///</summary>
        public const string IsOneOf = "ONEOF";
        ///<summary>
        /// Checks if the target value is none of the values listed.
        ///</summary>
        public const string IsNoneOf = "NONEOF";
        ///<summary>
        /// Checks if the target value is less than the specified values.
        ///</summary>
        public const string IsLessThan = "LESS";
        ///<summary>
        /// Checks if the target value is not less than the specified values.
        ///</summary>
        public const string IsNotLessThan = "NOTLESS";
        ///<summary>
        /// Checks if the target value is greater than the specified values.
        ///</summary>
        public const string IsGreaterThan = "GREATER";
        ///<summary>
        /// Checks if the target value is not greater than the specified values.
        ///</summary>
        public const string IsNotGreaterThan = "NOTGREATER";
        ///<summary>
        /// Checks if the target date/time is earlier than the specified date/time.
        ///</summary>
        public const string IsEarlierThan = "EARLIER";
        ///<summary>
        /// Checks if the target date/time is later than the specified date/time.
        ///</summary>
        public const string IsLaterThan = "LATER";
        ///<summary>
        /// Checks if the target value is between the specified values.
        ///</summary>
        public const string IsBetween = "BETWEEN";
        ///<summary>
        /// Checks if the target value contains the specified string.
        ///</summary>
        public const string Contains = "CONT";
        ///<summary>
        /// Checks if the target value does not contain the specified string.
        ///</summary>
        public const string DoesNotContain = "NOTCONT";
    }
    #endregion

    #region Yesno
    public class Yesno
    {
        ///<summary>
        /// Enumeration name used for storing it in a lookup cache.
        ///</summary>
        public const string EnumName = "yesno";

        public const string Yes = "true";
        public const string No = "false";
    }
    #endregion

}
