//---------------------------------------------------------------------------------------------
// This file was AUTO-GENERATED by "Service Contracts" Xomega.Net generator.
//
// Manual CHANGES to this file WILL BE LOST when the code is regenerated.
//---------------------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using Xomega.Framework.Services;

namespace AdventureWorks.Services.Common
{
    #region ISpecialOfferService interface

    ///<summary>
    /// Sale discounts lookup table.
    ///</summary>
    public interface ISpecialOfferService
    {

        ///<summary>
        /// Reads enumeration data for Special Offer.
        ///</summary>
        Task<Output<ICollection<SpecialOffer_ReadEnumOutput>>> ReadEnumAsync(CancellationToken token = default);

    }
    #endregion

    #region SpecialOffer_ReadEnumOutput structure

    ///<summary>
    /// The output structure of operation ISpecialOfferService.ReadEnumAsync.
    ///</summary>
    public class SpecialOffer_ReadEnumOutput
    {

        public int SpecialOfferId { get; set; }

        ///<summary>
        /// Discount description.
        ///</summary>
        public string Description { get; set; }

        public bool IsActive { get; set; }

        ///<summary>
        /// Group the discount applies to such as Reseller or Customer.
        ///</summary>
        public string Category { get; set; }
    }
    #endregion

}