//---------------------------------------------------------------------------------------------
// This file was AUTO-GENERATED by "Xomega Data Objects" Xomega.Net generator.
//
// Manual CHANGES to this file WILL BE LOST when the code is regenerated.
//---------------------------------------------------------------------------------------------

using AdventureWorks.Client.Objects;
using AdventureWorks.Enumerations;
using AdventureWorks.Services;
using System;
using System.Data.Spatial;
using Xomega.Framework;
using Xomega.Framework.Properties;

namespace AdventureWorks.Client.Objects
{
    public partial class SalesOrderReasonObject : DataObject
    {
        #region Constants

        public const string ModifiedDate = "ModifiedDate";
        public const string SalesOrderId = "SalesOrderId";
        public const string SalesReasonId = "SalesReasonId";

        #endregion

        #region Properties

        public DateTimeProperty ModifiedDateProperty { get; private set; }
        public IntegerKeyProperty SalesOrderIdProperty { get; private set; }
        public IntegerKeyProperty SalesReasonIdProperty { get; private set; }

        #endregion

        #region Construction

        protected override void Initialize()
        {
            ModifiedDateProperty = new DateTimeProperty(this, ModifiedDate);
            ModifiedDateProperty.Required = true;
            SalesOrderIdProperty = new IntegerKeyProperty(this, SalesOrderId);
            SalesOrderIdProperty.Required = true;
            SalesOrderIdProperty.Editable = false;
            SalesReasonIdProperty = new IntegerKeyProperty(this, SalesReasonId);
            SalesReasonIdProperty.Required = true;
            SalesReasonIdProperty.Editable = false;
        }

        #endregion
    }

}