//---------------------------------------------------------------------------------------------
// This file was AUTO-GENERATED by "Web API Controllers" Xomega.Net generator.
//
// Manual CHANGES to this file WILL BE LOST when the code is regenerated.
//---------------------------------------------------------------------------------------------

using Microsoft.Extensions.DependencyInjection;
using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Web.Http;
using Xomega.Framework;

namespace AdventureWorks.Services
{
    ///<summary>
    /// Products sold or used in the manfacturing of sold products.
    ///</summary>
    public partial class ProductController : ApiController
    {
        private ErrorParser errorParser;
        private IProductService svc;

        public ProductController(IServiceProvider serviceProvider)
        {
            errorParser = serviceProvider.GetService<ErrorParser>();
            svc = serviceProvider.GetService<IProductService>();
            if (svc is IPrincipalProvider)
                ((IPrincipalProvider)svc).CurrentPrincipal = RequestContext.Principal;
        }

        ///<summary>
        /// Reads a list of Product objects based on the specified criteria.
        ///</summary>
        [Route("product")]
        [HttpGet]
        public HttpResponseMessage ReadList()
        {
            HttpResponseMessage response = Request.CreateResponse();
            try
            {
                IEnumerable<Product_ReadListOutput> output = svc.ReadList();
                response = Request.CreateResponse(output);
            }
            catch (Exception ex)
            {
                ErrorList errors = errorParser.FromException(ex);
                response = Request.CreateResponse(errors);
                response.StatusCode = errors.HttpStatus;
            }
            return response;
        }
    }
}