//---------------------------------------------------------------------------------------------
// This file was AUTO-GENERATED by "View Models" Xomega.Net generator.
//
// Manual CHANGES to this file WILL BE LOST when the code is regenerated.
//---------------------------------------------------------------------------------------------

using AdventureWorks.Client.Objects;
using Microsoft.Extensions.DependencyInjection;
using System;
using Xomega.Framework.Views;

namespace AdventureWorks.Client.ViewModels
{
    public partial class LoginViewModel : DetailsViewModel
    {
        protected AuthenticationObject obj { get { return DetailsObject as AuthenticationObject; } }

        public LoginViewModel(IServiceProvider sp) : base(sp)
        {
        }

        public override void Initialize()
        {
            base.Initialize();
            DetailsObject = ServiceProvider.GetService<AuthenticationObject>();
        }
    }
}