<%---------------------------------------------------------------------------------------------
 This file was AUTO-GENERATED by "ASP.NET Search Pages" Xomega.Net generator.

 Manual CHANGES to this file WILL BE LOST when the code is regenerated.
----------------------------------------------------------------------------------------------%>

<%@ Page Title="Sales Order List" Language="C#" MasterPageFile="~/Site.master" Inherits="AdventureWorks.Client.Web.SalesOrderListViewPage" %>

<%@ Register src="~/Pages/Sales/SalesOrderListView.ascx" tagname="SalesOrderListView" tagprefix="uc" %>

<asp:Content ID="Main" ContentPlaceHolderID="MainContent" runat="server">
  <uc:SalesOrderListView ID="uclSalesOrderListView" runat="server"></uc:SalesOrderListView>
</asp:Content>