<%---------------------------------------------------------------------------------------------
 This file was AUTO-GENERATED by "ASP.NET Details Pages" Xomega.Net generator.

 Manual CHANGES to this file WILL BE LOST when the code is regenerated.
----------------------------------------------------------------------------------------------%>

<%@ Page Title="Sales Order" Language="C#" MasterPageFile="~/Site.master" Inherits="AdventureWorks.Client.Web.SalesOrderViewPage" %>

<%@ Register src="~/Pages/Sales/SalesOrderView.ascx" tagname="SalesOrderView" tagprefix="uc" %>

<asp:Content ID="Main" ContentPlaceHolderID="MainContent" runat="server">
  <uc:SalesOrderView ID="uclSalesOrderView" runat="server"></uc:SalesOrderView>
</asp:Content>