//---------------------------------------------------------------------------------------------
// This file was AUTO-GENERATED by "ASP.NET Details Pages" Xomega.Net generator.
//
// Manual CHANGES to this file WILL BE LOST when the code is regenerated.
//---------------------------------------------------------------------------------------------

namespace AdventureWorks.Client.Web
{
    public partial class SalesOrderReasonView
    {
        protected global::System.Web.UI.WebControls.Panel pnlComposition;
        protected global::System.Web.UI.WebControls.Panel pnlSalesOrderReasonView;
        protected global::System.Web.UI.WebControls.Label lblSalesOrderReasonViewTitle;
        protected global::AdventureWorks.Client.Web.Errors errors;
        protected global::System.Web.UI.WebControls.Panel pnlMain;
        protected global::System.Web.UI.WebControls.Label lblSalesOrderId;
        protected global::System.Web.UI.WebControls.Label ctlSalesOrderId;
        protected global::System.Web.UI.WebControls.Label lblSalesReasonId;
        protected global::System.Web.UI.WebControls.Label ctlSalesReasonId;
        protected global::System.Web.UI.WebControls.Label lblModifiedDate;
        protected global::AdventureWorks.Client.Web.DateTimeControl ctlModifiedDate;
        protected global::System.Web.UI.WebControls.Button btnSave;
        protected global::System.Web.UI.WebControls.Button btnDelete;
    }
}