//---------------------------------------------------------------------------------------------
// This file was AUTO-GENERATED by "ASP.NET Details Pages" Xomega.Net generator.
//
// Manual CHANGES to this file WILL BE LOST when the code is regenerated.
//---------------------------------------------------------------------------------------------

namespace AdventureWorks.Client.Web
{
    public partial class SalesOrderView
    {
        protected global::System.Web.UI.WebControls.Panel pnlComposition;
        protected global::System.Web.UI.WebControls.Panel pnlSalesOrderView;
        protected global::System.Web.UI.WebControls.Label lblSalesOrderViewTitle;
        protected global::AdventureWorks.Client.Web.Errors errors;
        protected global::System.Web.UI.WebControls.Panel pnlMain;
        protected global::System.Web.UI.WebControls.Label lblSalesOrderNumber;
        protected global::System.Web.UI.WebControls.Label ctlSalesOrderNumber;
        protected global::System.Web.UI.WebControls.Label lblOrderDate;
        protected global::System.Web.UI.WebControls.Label ctlOrderDate;
        protected global::System.Web.UI.WebControls.Label lblStatus;
        protected global::System.Web.UI.WebControls.DropDownList ctlStatus;
        protected global::System.Web.UI.WebControls.Label lblOnlineOrderFlag;
        protected global::System.Web.UI.WebControls.CheckBox ctlOnlineOrderFlag;
        protected global::System.Web.UI.WebControls.Label lblPurchaseOrderNumber;
        protected global::System.Web.UI.WebControls.TextBox ctlPurchaseOrderNumber;
        protected global::System.Web.UI.WebControls.Label lblAccountNumber;
        protected global::System.Web.UI.WebControls.TextBox ctlAccountNumber;
        protected global::System.Web.UI.WebControls.Label lblCustomerId;
        protected global::System.Web.UI.WebControls.TextBox ctlCustomerId;
        protected global::System.Web.UI.WebControls.Label lblSalesPersonId;
        protected global::System.Web.UI.WebControls.DropDownList ctlSalesPersonId;
        protected global::System.Web.UI.WebControls.Label lblTerritoryId;
        protected global::System.Web.UI.WebControls.DropDownList ctlTerritoryId;
        protected global::System.Web.UI.WebControls.Label lblBillToAddressId;
        protected global::System.Web.UI.WebControls.TextBox ctlBillToAddressId;
        protected global::System.Web.UI.WebControls.Label lblShipToAddressId;
        protected global::System.Web.UI.WebControls.TextBox ctlShipToAddressId;
        protected global::System.Web.UI.WebControls.Label lblShipDate;
        protected global::AdventureWorks.Client.Web.DateTimeControl ctlShipDate;
        protected global::System.Web.UI.WebControls.Label lblComment;
        protected global::System.Web.UI.WebControls.TextBox ctlComment;
        protected global::System.Web.UI.WebControls.Label lblRevisionNumber;
        protected global::System.Web.UI.WebControls.Label ctlRevisionNumber;
        protected global::System.Web.UI.WebControls.Label lblModifiedDate;
        protected global::System.Web.UI.WebControls.Label ctlModifiedDate;
        protected global::AjaxControlToolkit.TabContainer tbcChildren;
        protected global::AjaxControlToolkit.TabPanel tabDetail;
        protected global::System.Web.UI.WebControls.Panel pnlDetail;
        protected global::System.Web.UI.WebControls.GridView gridDetail;
        protected global::System.Web.UI.WebControls.LinkButton lnkDetailNew;
        protected global::AjaxControlToolkit.TabPanel tabPayment;
        protected global::System.Web.UI.WebControls.Panel pnlPayment;
        protected global::System.Web.UI.WebControls.Label lblPaymentSubTotal;
        protected global::System.Web.UI.WebControls.Label ctlPaymentSubTotal;
        protected global::System.Web.UI.WebControls.Label lblPaymentShipMethodId;
        protected global::System.Web.UI.WebControls.DropDownList ctlPaymentShipMethodId;
        protected global::System.Web.UI.WebControls.Label lblPaymentTaxAmt;
        protected global::System.Web.UI.WebControls.Label ctlPaymentTaxAmt;
        protected global::System.Web.UI.WebControls.Label lblPaymentFreight;
        protected global::System.Web.UI.WebControls.Label ctlPaymentFreight;
        protected global::System.Web.UI.WebControls.Label lblPaymentTotalDue;
        protected global::System.Web.UI.WebControls.Label ctlPaymentTotalDue;
        protected global::System.Web.UI.WebControls.Label lblPaymentDueDate;
        protected global::AdventureWorks.Client.Web.DateTimeControl ctlPaymentDueDate;
        protected global::System.Web.UI.WebControls.Label lblPaymentCurrencyRate;
        protected global::System.Web.UI.WebControls.Label ctlPaymentCurrencyRate;
        protected global::System.Web.UI.WebControls.Label lblPaymentCreditCardId;
        protected global::System.Web.UI.WebControls.TextBox ctlPaymentCreditCardId;
        protected global::System.Web.UI.WebControls.Label lblPaymentCreditCardApprovalCode;
        protected global::System.Web.UI.WebControls.TextBox ctlPaymentCreditCardApprovalCode;
        protected global::AjaxControlToolkit.TabPanel tabReason;
        protected global::System.Web.UI.WebControls.Panel pnlReason;
        protected global::System.Web.UI.WebControls.GridView gridReason;
        protected global::System.Web.UI.WebControls.LinkButton lnkReasonNew;
        protected global::System.Web.UI.WebControls.Button btnSave;
        protected global::System.Web.UI.WebControls.Button btnDelete;
        protected global::System.Web.UI.UpdatePanel uplSalesOrderDetailView;
        protected global::AdventureWorks.Client.Web.SalesOrderDetailView uclSalesOrderDetailView;
        protected global::System.Web.UI.UpdatePanel uplSalesOrderReasonView;
        protected global::AdventureWorks.Client.Web.SalesOrderReasonView uclSalesOrderReasonView;
    }
}