//---------------------------------------------------------------------------------------------
// This file was AUTO-GENERATED by "Lookup Cache Loaders" Xomega.Net generator.
//
// Manual CHANGES to this file WILL BE LOST when the code is regenerated.
//---------------------------------------------------------------------------------------------

using Microsoft.Extensions.DependencyInjection;
using System;
using System.Collections.Generic;
using Xomega.Framework;
using Xomega.Framework.Lookup;

namespace AdventureWorks.Services
{
    public partial class SpecialOfferReadListCacheLoader : LookupCacheLoader 
    {
        public SpecialOfferReadListCacheLoader(IServiceProvider serviceProvider)
            : base(serviceProvider, LookupCache.Global, true, "special offer")
        {
        }

        protected virtual IEnumerable<SpecialOffer_ReadListOutput> ReadList()
        {
            using (var s = serviceProvider.CreateScope())
            {
                return s.ServiceProvider.GetService<ISpecialOfferService>().ReadList();
            }
        }

        protected override void LoadCache(string tableType, CacheUpdater updateCache)
        {
            Dictionary<string, Dictionary<string, Header>> data = new Dictionary<string, Dictionary<string, Header>>();
            foreach (SpecialOffer_ReadListOutput row in ReadList())
            {
                string type = "special offer";
                Dictionary<string, Header> tbl;
                if (!data.TryGetValue(type, out tbl)) data[type] = tbl = new Dictionary<string, Header>();

                string id = "" + row.SpecialOfferId;
                Header h;
                if (!tbl.TryGetValue(id, out h))
                {
                    tbl[id] = h = new Header(type, id, row.Description);
                    h.IsActive = row.IsActive;
                }
                h.AddToAttribute("category", row.Category);
            }
            // if no data is returned we still need to update cache to get the notify listener removed
            if (data.Count == 0) updateCache(new LookupTable(tableType, new List<Header>(), true));
            foreach (string type in data.Keys)
                updateCache(new LookupTable(type, data[type].Values, true));
        }
    }
}