//---------------------------------------------------------------------------------------------
// This file was AUTO-GENERATED by "EF Domain Objects" Xomega.Net generator.
//
// Manual CHANGES to this file WILL BE LOST when the code is regenerated.
//---------------------------------------------------------------------------------------------

using System;

namespace AdventureWorks.Services.Entities
{
    ///<summary>
    /// Lookup table containing the languages in which some AdventureWorks data is stored.
    ///</summary>
    public partial class Culture
    {
        public Culture()
        {
        }

        #region Properties

        public string CultureId  { get; set; }

        ///<summary>
        /// Culture description.
        ///</summary>
        public string Name  { get; set; }

        ///<summary>
        /// Date and time the record was last updated.
        ///</summary>
        public DateTime ModifiedDate  { get; set; }

        #endregion
    }
}