//---------------------------------------------------------------------------------------------
// This file was AUTO-GENERATED by "EF Domain Objects" Xomega.Net generator.
//
// Manual CHANGES to this file WILL BE LOST when the code is regenerated.
//---------------------------------------------------------------------------------------------

using System;

namespace AdventureWorks.Services.Entities
{
    ///<summary>
    /// Product model classification.
    ///</summary>
    public partial class ProductModel
    {
        public ProductModel()
        {
        }

        #region Properties

        public int ProductModelId  { get; set; }

        ///<summary>
        /// Product model description.
        ///</summary>
        public string Name  { get; set; }

        ///<summary>
        /// Detailed product catalog information in xml format.
        ///</summary>
        public string CatalogDescription  { get; set; }

        ///<summary>
        /// Manufacturing instructions in xml format.
        ///</summary>
        public string Instructions  { get; set; }

        ///<summary>
        /// ROWGUIDCOL number uniquely identifying the record. Used to support a merge replication sample.
        ///</summary>
        public Guid Rowguid  { get; set; }

        ///<summary>
        /// Date and time the record was last updated.
        ///</summary>
        public DateTime ModifiedDate  { get; set; }

        #endregion
    }
}