//---------------------------------------------------------------------------------------------
// This file was AUTO-GENERATED by "EF Domain Objects" Xomega.Net generator.
//
// Manual CHANGES to this file WILL BE LOST when the code is regenerated.
//---------------------------------------------------------------------------------------------

using System;

namespace AdventureWorks.Services.Entities
{
    ///<summary>
    /// Changes in the cost of a product over time.
    ///</summary>
    public partial class ProductCostHistory
    {
        public ProductCostHistory()
        {
        }

        #region Properties

        ///<summary>
        /// Product identification number. Foreign key to Product.ProductID
        ///</summary>
        public int ProductId  { get; set; }

        ///<summary>
        /// Product cost start date.
        ///</summary>
        public DateTime StartDate  { get; set; }

        ///<summary>
        /// Product cost end date.
        ///</summary>
        public DateTime? EndDate  { get; set; }

        ///<summary>
        /// Standard cost of the product.
        ///</summary>
        public decimal StandardCost  { get; set; }

        ///<summary>
        /// Date and time the record was last updated.
        ///</summary>
        public DateTime ModifiedDate  { get; set; }

        #endregion

        #region Navigation Properties

        ///<summary>
        /// Product object referenced by the field ProductId.
        ///</summary>
        public virtual Product ProductObject { get; set; }

        #endregion
    }
}