//---------------------------------------------------------------------------------------------
// This file was AUTO-GENERATED by "EF Domain Objects" Xomega.Net generator.
//
// Manual CHANGES to this file WILL BE LOST when the code is regenerated.
//---------------------------------------------------------------------------------------------

using System;

namespace AdventureWorks.Services.Entities
{
    ///<summary>
    /// Unit of measure lookup table.
    ///</summary>
    public partial class UnitMeasure
    {
        public UnitMeasure()
        {
        }

        #region Properties

        public string UnitMeasureCode  { get; set; }

        ///<summary>
        /// Unit of measure description.
        ///</summary>
        public string Name  { get; set; }

        ///<summary>
        /// Date and time the record was last updated.
        ///</summary>
        public DateTime ModifiedDate  { get; set; }

        #endregion
    }
}