//---------------------------------------------------------------------------------------------
// This file was AUTO-GENERATED by "EF Domain Objects" Xomega.Net generator.
//
// Manual CHANGES to this file WILL BE LOST when the code is regenerated.
//---------------------------------------------------------------------------------------------

using System;

namespace AdventureWorks.Services.Entities
{
    ///<summary>
    /// Work order details.
    ///</summary>
    public partial class WorkOrderRouting
    {
        public WorkOrderRouting()
        {
        }

        #region Properties

        ///<summary>
        /// Primary key. Foreign key to WorkOrder.WorkOrderID.
        ///</summary>
        public int WorkOrderId  { get; set; }

        ///<summary>
        /// Primary key. Foreign key to Product.ProductID.
        ///</summary>
        public int ProductId  { get; set; }

        ///<summary>
        /// Primary key. Indicates the manufacturing process sequence.
        ///</summary>
        public short OperationSequence  { get; set; }

        ///<summary>
        /// Manufacturing location where the part is processed. Foreign key to Location.LocationID.
        ///</summary>
        public short LocationId  { get; set; }

        ///<summary>
        /// Planned manufacturing start date.
        ///</summary>
        public DateTime ScheduledStartDate  { get; set; }

        ///<summary>
        /// Planned manufacturing end date.
        ///</summary>
        public DateTime ScheduledEndDate  { get; set; }

        ///<summary>
        /// Actual start date.
        ///</summary>
        public DateTime? ActualStartDate  { get; set; }

        ///<summary>
        /// Actual end date.
        ///</summary>
        public DateTime? ActualEndDate  { get; set; }

        ///<summary>
        /// Number of manufacturing hours used.
        ///</summary>
        public decimal? ActualResourceHrs  { get; set; }

        ///<summary>
        /// Estimated manufacturing cost.
        ///</summary>
        public decimal PlannedCost  { get; set; }

        ///<summary>
        /// Actual manufacturing cost.
        ///</summary>
        public decimal? ActualCost  { get; set; }

        ///<summary>
        /// Date and time the record was last updated.
        ///</summary>
        public DateTime ModifiedDate  { get; set; }

        #endregion

        #region Navigation Properties

        ///<summary>
        /// WorkOrder object referenced by the field WorkOrderId.
        ///</summary>
        public virtual WorkOrder WorkOrderObject { get; set; }

        ///<summary>
        /// Location object referenced by the field LocationId.
        ///</summary>
        public virtual Location LocationObject { get; set; }

        #endregion
    }
}