//---------------------------------------------------------------------------------------------
// This file was AUTO-GENERATED by "TS Service Contracts" Xomega.Net generator.
//
// Manual CHANGES to this file WILL BE LOST when the code is regenerated.
//---------------------------------------------------------------------------------------------

import * as $ from 'jquery';
import { AuthManager } from 'xomega';

export class IProductService {

    public static getReadListRequest(): JQueryAjaxSettings {
        let req: JQueryAjaxSettings = AuthManager.Current.createAjaxRequest();
        req.type = 'GET';
        req.url += `product`;
        return req;
    }
}

export class Product_ReadListOutput {
    public ProductId: any;
    public Name: any;
    public IsActive: any;
    public ProductSubcategoryId: any;
    public ProductModelId: any;
}