//---------------------------------------------------------------------------------------------
// This file was AUTO-GENERATED by "REST Service Clients" Xomega.Net generator.
//
// Manual CHANGES to this file WILL BE LOST when the code is regenerated.
//---------------------------------------------------------------------------------------------

using Microsoft.Extensions.Options;
using System;
using System.Net.Http;
using System.Text.Json;
using System.Threading.Tasks;
using Xomega.Framework.Services;

namespace AdventureWorks.Services
{
    ///<summary>
    /// Human beings involved with AdventureWorks: employees, customer contacts, and vendor contacts.
    ///</summary>
    public class PersonServiceClient : HttpServiceClient, IPersonService
    {
        protected readonly JsonSerializerOptions SerializerOptions;

        public PersonServiceClient(HttpClient httpClient, IOptionsMonitor<JsonSerializerOptions> options)
            : base(httpClient)
        {
            SerializerOptions = options.CurrentValue;
        }

        /// <inheritdoc/>
        public virtual async Task<Output> AuthenticateAsync(Credentials _credentials)
        {
            await Task.CompletedTask;
            throw new NotSupportedException("Operation IPersonService.AuthenticateAsync is not exposed via REST.");
        }

        /// <inheritdoc/>
        public virtual async Task<Output<PersonInfo>> ReadAsync(string _email)
        {
            await Task.CompletedTask;
            throw new NotSupportedException("Operation IPersonService.ReadAsync is not exposed via REST.");
        }
    }
}