//---------------------------------------------------------------------------------------------
// This file was AUTO-GENERATED by "TS Service Contracts" Xomega.Net generator.
//
// Manual CHANGES to this file WILL BE LOST when the code is regenerated.
//---------------------------------------------------------------------------------------------

import * as $ from 'jquery';
import { AuthManager } from 'xomega';

export class ISalesTerritoryService {

    public static getReadListRequest(): JQueryAjaxSettings {
        let req: JQueryAjaxSettings = AuthManager.Current.createAjaxRequest();
        req.type = 'GET';
        req.url += `sales-territory`;
        return req;
    }
}

export class SalesTerritory_ReadListOutput {
    public TerritoryId: any;
    public Name: any;
    public CountryRegionCode: any;
    public Group: any;
}