//---------------------------------------------------------------------------------------------
// This file was AUTO-GENERATED by "TS Service Contracts" Xomega.Net generator.
//
// Manual CHANGES to this file WILL BE LOST when the code is regenerated.
//---------------------------------------------------------------------------------------------

import * as $ from 'jquery';
import { AuthManager } from 'xomega';

export class ISpecialOfferService {

    public static getReadListRequest(): JQueryAjaxSettings {
        let req: JQueryAjaxSettings = AuthManager.Current.createAjaxRequest();
        req.type = 'GET';
        req.url += `special-offer`;
        return req;
    }
}

export class SpecialOffer_ReadListOutput {
    public SpecialOfferId: any;
    public Description: any;
    public IsActive: any;
    public Category: any;
}