//---------------------------------------------------------------------------------------------
// This file was AUTO-GENERATED by "SPA Views" Xomega.Net generator.
//
// Manual CHANGES to this file WILL BE LOST when the code is regenerated.
//---------------------------------------------------------------------------------------------

export var MainMenu = [
    {
        title: 'Sales', items: [
            { title: 'Customer List', route: 'CustomerListView', hash: '' },
            { title: 'New Sales Order', route: 'SalesOrderView', hash: '#SalesOrderView?_action=create' },
            { title: 'Sales Order List', route: 'SalesOrderListView', hash: '' },
        ]
    },
];